version: '3.5'
services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: zoookeeper1
      zk_id: "1"
      ZOOKEEPER_CLIENT_PORT: 2181
      EXTRA_ARGS: -javaagent:/usr/share/jmx_exporter/applicationinsights-agent-3.0.2.jar=1234:/usr/share/jmx_exporter/zookeeper.yml
    volumes:
    - ./app_insights/applicationinsights.json:/usr/share/jmx_exporter/applicationinsights.json
    - ./app_insights/applicationinsights-agent-3.0.2.jar:/usr/share/jmx_exporter/applicationinsights-agent-3.0.2.jar
    - ./app_insights/applicationinsights-agent-3.0.2.jar:/usr/share/jmx_exporter/zookeeper.yml

  broker1:
    image: confluentinc/cp-kafka:latest
    hostname: broker1
    container_name: broker1
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper1
    environment:
      KAFKA_JMX_PORT: 10000
      KAFKA_JMX_HOSTNAME: broker1
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: "1"
      KAFKA_LOG4J_ROOT_LOGLEVEL: "INFO"
      KAFKA_BROKER_ID: "1"

  broker2:
    image: confluentinc/cp-kafka:latest
    hostname: broker2
    container_name: broker2
    ports:
      - '9093:9093'
    depends_on:
      - zookeeper1
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker2:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: "1"
      KAFKA_LOG4J_ROOT_LOGLEVEL: "INFO"
      KAFKA_BROKER_ID: "2"

  broker3:
    image: confluentinc/cp-kafka:latest
    hostname: broker3
    container_name: broker3
    ports:
      - '9094:9094'
    depends_on:
      - zookeeper1
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker3:19094,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: "1"
      KAFKA_LOG4J_ROOT_LOGLEVEL: "INFO"
      KAFKA_BROKER_ID: "3"